### ISSUE TITLE
config.txt doesn't work on Raspian Buster / Retropie

### ISSUE THREAD

**Issue by lazydays79** [kristijandraca/GPi_Case_patch#1]
Hi!

I just downloaded the newest retropie image (retropie-buster-4.8-rpi1_zero.img). Everything works fine, except for sound.

ALSA doesn't see any soundcards.

Is there a workaround?

Lind regards,
Michael

**Comment by branttaylor** [comment]
Same issue here. Anybody found a fix for this?

**Comment by kristijandraca** [comment]
Hi, I don't work for retroflag, nor am I associated with them in any way. This repo is just a .sh translation of their .bat script. If you need support for your GPi case, please connect with retroflag directly.
